name: Deploy

on:
  push:
    branches:
      - dev
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Generate service worker
        run: npx workbox-cli generateSW workbox-config.js

      - name: Upload to S3
        run: |
          aws s3 sync \
            . \
            s3://${{ secrets.S3_BUCKET }}/ \
            --delete \
            --exclude ".*" \
            --exclude "README.md"

      - name: Set no-cache on the service worker
        run: |
          aws s3 cp \
            s3://${{ secrets.S3_BUCKET}}/sw.js \
            s3://${{ secrets.S3_BUCKET }}/sw.js \
            --metadata-directive REPLACE \
            --cache-control no-cache

      - name: Invalidate Cloudfront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_ID }} \
            --paths "/*"
